### ISSUE TITLE
[FLASH_SPI] Add support for HW CS

### ISSUE THREAD

**Issue by elsalahy** [TheThingsIndustries/generic-node-se#40]
**Summary:** 

Currently, we use SW CS as a normal GPIO to intiate the SPI transfers to the external flash.

**Why do we need this?**

To have faster SPI transfers and fully utilize the SOC features.

**What is already there? What do you see now?**

SW GPIO control of the CS pin.

**What is missing? What do you want to see?**

HW control of the SPI core.

**How do you propose to implement this?**

- Configure the SPI core to use a HW CS pin
- Adjust any driver (like the external flash) to use the HW version instead of the SW (just remove the manual SW GPIO control).

**Environment:**

Baremetal.

**Acceptance Criteria:**

- SPI functionality behaves the same as the SW one.
- Adapt the change if there is an improvement in the speed.

**What can you do yourself and what do you need help with?**

ALL

**Comment by marnixcrouzen** [comment]
**Update on findings, should this issue be delayed**
HW CS works a little different than anticipated, but might still work. 
This is the diagram for the first command of the basic app (getting the ID), note that the CS pin has to be released, it will otherwise send the ID continuously.
![image](https://user-images.githubusercontent.com/77615373/109627493-f943e880-7b41-11eb-8c20-5aa164542f4a.png)

I've gathered some images of the CS pin and the SCL pin during this command (MOSI is always correct, no need to display).

SW of course works:
![image](https://user-images.githubusercontent.com/77615373/109625576-c698f080-7b3f-11eb-821a-68b1e3f37c3d.png)

HW CS has two modes on the STM32, pulsed enabled or disabled mode.
Pulse disables seems to be just letting CS be low forever to gets this:
![image](https://user-images.githubusercontent.com/77615373/109625802-09f35f00-7b40-11eb-939b-1ab54c1872d8.png)
This gets the proper ID, but fails when doing anything else as the flash IC will from then on respond to anything with the ID number since the CS pin was never released.

Pulse enables doesn't get as far as receiving the ID. It sets CS pin high whenever SPI is free:
![image](https://user-images.githubusercontent.com/77615373/109626107-69516f00-7b40-11eb-8789-317e49969d58.png)
Since the CS pin is released every time the SPI interface seems to be free, the message gets interrupted and the flash IC thinks its nothing.

How to fix:

- **Pulse enabled**, make sure SPI is not freed in between, see if that's possible when sending multiple bytes. This would be the best solution as it would work similarly to the current SW NSS whilst being faster.
- **Pulse disabled**, find out when the CS pin is released. From this [link](https://stackoverflow.com/questions/35780290/how-to-use-hardware-nss-spi-on-stm32f4) the answer is turning off the whole SPI interface (doesn't really make HW SPI that nice tbh).
- **Dirty fix**, Do not receive the ID and work with pulse disabled mode, other commands (reading/writing) do not care if the CS pin is set high at the end

**Comment by elsalahy** [comment]
@marnixcrouzen Thanks for the detailed/great analysis.

I think we should not proceed forward with this issue, and we should close it, as with the current external flash (MX25R1635F) and supported STM32 SPI modes, it is clear that this will not be a viable solution.

This can be re-opened in the future if we change the MCU or the external flash.

To make sure we maximize the gain from your investigation, please document the following in this issue.
1. How to enable pulse enabled (provide source code)
2. How to enable pulse disabled (provide source code)
3. SPI transmission example using HW CS (provide source code).

And afterwords please close the issue.

**Comment by marnixcrouzen** [comment]
Diff file shows for enabling pulse, NSSPMode should be kept SPI_NSS_PULSE_DISABLE for disabled pulse. Setting the frequency of the pin high is not required, but seemed useful when trying to optimise speed.
```diff
diff --git a/Software/lib/GNSE_BSP/GNSE_bsp_serial.c b/Software/lib/GNSE_BSP/GNSE_bsp_serial.c
index 1a87a20..4911631 100644
--- a/Software/lib/GNSE_BSP/GNSE_bsp_serial.c
+++ b/Software/lib/GNSE_BSP/GNSE_bsp_serial.c
@@ -175,14 +175,14 @@ int32_t GNSE_BSP_Flash_SPI_Init(void)
   GNSE_BSP_flash_spi.Init.DataSize = SPI_DATASIZE_8BIT;
   GNSE_BSP_flash_spi.Init.CLKPolarity = SPI_POLARITY_LOW;
   GNSE_BSP_flash_spi.Init.CLKPhase = SPI_PHASE_1EDGE;
-  GNSE_BSP_flash_spi.Init.NSS = SPI_NSS_SOFT; //TODO: USE HW NSS, see https://github.com/TheThingsIndustries/generic-node-se/issues/40
+  GNSE_BSP_flash_spi.Init.NSS = SPI_NSS_HARD_OUTPUT;
   GNSE_BSP_flash_spi.Init.BaudRatePrescaler = FLASH_SPI_BAUDRATE;
   GNSE_BSP_flash_spi.Init.FirstBit = SPI_FIRSTBIT_MSB;
   GNSE_BSP_flash_spi.Init.TIMode = SPI_TIMODE_DISABLE;
   GNSE_BSP_flash_spi.Init.CRCCalculation = SPI_CRCCALCULATION_DISABLE;
   GNSE_BSP_flash_spi.Init.CRCPolynomial = 7;
   GNSE_BSP_flash_spi.Init.CRCLength = SPI_CRC_LENGTH_DATASIZE;
-  GNSE_BSP_flash_spi.Init.NSSPMode = SPI_NSS_PULSE_DISABLE;
+  GNSE_BSP_flash_spi.Init.NSSPMode = SPI_NSS_PULSE_ENABLE;
   if (HAL_SPI_Init(&GNSE_BSP_flash_spi) != HAL_OK)
   {
     return GNSE_BSP_ERROR_NO_INIT;
diff --git a/Software/lib/GNSE_BSP/GNSE_msp.c b/Software/lib/GNSE_BSP/GNSE_msp.c
index 81abcb7..a4b96e3 100644
--- a/Software/lib/GNSE_BSP/GNSE_msp.c
+++ b/Software/lib/GNSE_BSP/GNSE_msp.c
@@ -187,14 +187,13 @@ void HAL_SPI_MspInit(SPI_HandleTypeDef *spiHandle)
         FLASH_SPI_GPIO_CLK_ENABLE();

         /*Configure GPIO pin Output Level */
-        HAL_GPIO_WritePin(FLASH_SPI_GPIO_PORT, FLASH_SPI_CS_PIN, GPIO_PIN_RESET);

         gpio_init_structure.Pin = FLASH_SPI_CS_PIN;
-        gpio_init_structure.Mode = GPIO_MODE_OUTPUT_PP;
+        gpio_init_structure.Mode = GPIO_MODE_AF_PP;
         gpio_init_structure.Pull = GPIO_NOPULL;
-        gpio_init_structure.Speed = GPIO_SPEED_FREQ_LOW;
+        gpio_init_structure.Speed = GPIO_SPEED_FREQ_VERY_HIGH;
+        gpio_init_structure.Alternate = GPIO_AF5_SPI1;
         HAL_GPIO_Init(FLASH_SPI_GPIO_PORT, &gpio_init_structure);
-        HAL_GPIO_WritePin(FLASH_SPI_GPIO_PORT, FLASH_SPI_CS_PIN, GPIO_PIN_SET);

         gpio_init_structure.Pin = FLASH_SPI_MISO_PIN | FLASH_SPI_SCK_PIN;
         gpio_init_structure.Mode = GPIO_MODE_AF_PP;
diff --git a/Software/lib/MX25R1635/mxic_hc.c b/Software/lib/MX25R1635/mxic_hc.c
index 70fb103..a252565 100644
--- a/Software/lib/MX25R1635/mxic_hc.c
+++ b/Software/lib/MX25R1635/mxic_hc.c
@@ -53,15 +53,11 @@ int MxPolledTransfer(MxSpi *Spi, u8 *WrBuf, u8 *RdBuf, u32 ByteCount)
     HAL_StatusTypeDef status = HAL_OK;
     if (RdBuf == NULL)
     {
-        HAL_GPIO_WritePin(FLASH_SPI_GPIO_PORT, FLASH_SPI_CS_PIN, GPIO_PIN_RESET);
         status = HAL_SPI_Transmit(&GNSE_BSP_flash_spi, (uint8_t *)WrBuf, ByteCount, Flash_SPI_TIMOUT);
-        HAL_GPIO_WritePin(FLASH_SPI_GPIO_PORT, FLASH_SPI_CS_PIN, GPIO_PIN_SET);
     }
     else
     {
-        HAL_GPIO_WritePin(FLASH_SPI_GPIO_PORT, FLASH_SPI_CS_PIN, GPIO_PIN_RESET);
         status = HAL_SPI_TransmitReceive(&GNSE_BSP_flash_spi, (uint8_t *)WrBuf, (uint8_t *)RdBuf, ByteCount, Flash_SPI_TIMOUT);
-        HAL_GPIO_WritePin(FLASH_SPI_GPIO_PORT, FLASH_SPI_CS_PIN, GPIO_PIN_SET);
     }

     if (status != HAL_OK)

```
